smart_lamp_ui/lib/smart_lamp_ui_web/router.ex
defmodule SmartLampUiWeb.Router do
  use SmartLampUiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SmartLampUiWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SmartLampUiWeb do
    pipe_through :browser

    get "/", PageController, :index

    live "/lamps/:name", LampLive, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", SmartLampUiWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SmartLampUiWeb.Telemetry
    end
  end
end

smart_lamp_ui/lib/smart_lamp_ui/application.ex
defmodule SmartLampUi.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      SmartLampUiWeb.Telemetry,
      {SmartLamp.Supervisor, lamps: get_lamps_def()},
      # Start the PubSub system
      {Phoenix.PubSub, name: SmartLampUi.PubSub},
      # Start the Endpoint (http/https)
      SmartLampUiWeb.Endpoint
      # Start a worker by calling: SmartLampUi.Worker.start_link(arg)
      # {SmartLampUi.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: SmartLampUi.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    SmartLampUiWeb.Endpoint.config_change(changed, removed)
    :ok
  end

  defp get_lamps_def() do
    case Application.get_env(:smart_lamp, :lamps) do
      nil -> []
      # in a real project I would think this through more
      lamps -> with_ui_handler(lamps)
    end
  end

  defp with_ui_handler(lamps) do
    Enum.map(lamps, fn lamp ->
      Map.put(lamp, :button_handler, &SmartLampUi.broadcast_button_event/0)
    end)
  end
end

smart_lamp_ui/lib/smart_lamp_ui_web/controllers/page_controller.ex
defmodule SmartLampUiWeb.PageController do
  use SmartLampUiWeb, :controller

  def index(conn, _params) do
    lamps = SmartLamp.lamps()
    render(conn, "index.html", lamps: lamps)
  end
end

smart_lamp_ui/lib/smart_lamp_ui_web/live/lamp_live.ex
defmodule SmartLampUiWeb.LampLive do
  use SmartLampUiWeb, :live_view

  @impl true
  def render(assigns) do
    ~L"""
    <h1><%= @name %></h1>

    <p><%= @value %></p>

    <button phx-click="turn_on">ON</button>
    <button phx-click="turn_off">OFF</button>
    """
  end

  @impl true
  def mount(%{"name" => lamp_name}, _session, socket) do
    if connected?(socket), do: SmartLampUi.subscribe_button_event()

    {:ok,
     socket |> assign(:name, lamp_name) |> assign(:value, SmartLampUi.get_lamp_value(lamp_name))}
  end

  @impl true
  def handle_event("turn_on", _value, socket) do
    case socket.assigns[:value] do
      :on ->
        {:noreply, socket}

      :off ->
        do_toggle(socket)
    end
  end

  def handle_event("turn_off", _value, socket) do
    case socket.assigns[:value] do
      :off ->
        {:noreply, socket}

      :on ->
        do_toggle(socket)
    end
  end

  defp do_toggle(socket) do
    new_value = SmartLampUi.toggle!(socket.assigns[:name])
    {:noreply, socket |> assign(:value, new_value)}
  end

  @impl true
  def handle_info(:button_pressed, socket) do
    {:noreply, assign(socket, :value, SmartLampUi.get_lamp_value(socket.assigns[:name]))}
  end
end

smart_lamp_ui/lib/smart_lamp_ui_web/views/error_view.ex
defmodule SmartLampUiWeb.ErrorView do
  use SmartLampUiWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

smart_lamp_ui/lib/smart_lamp_ui_web/views/layout_view.ex
defmodule SmartLampUiWeb.LayoutView do
  use SmartLampUiWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

smart_lamp_ui/lib/smart_lamp_ui_web/views/page_view.ex
defmodule SmartLampUiWeb.PageView do
  use SmartLampUiWeb, :view

  def display_name(lamp_name) when is_atom(lamp_name) do
    Atom.to_string(lamp_name)
  end

  def display_name(lamp_name), do: lamp_name
end

smart_lamp_ui/lib/smart_lamp_ui_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

smart_lamp_ui/lib/smart_lamp_ui_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

smart_lamp_ui/lib/smart_lamp_ui_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "SmartLampUi", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

smart_lamp_ui/lib/smart_lamp_ui_web/templates/page/index.html.heex
<ul>
  <%= for l <- @lamps do %>
    <li>
      <%= link(display_name(l), to: Routes.lamp_path(@conn, :show, display_name(l))) %>
    </li>
  <% end %>
</ul>